### ISSUE TITLE
jshintrc config expects dir

### ISSUE THREAD

**Issue by enapupe** [kylewelsby/karma-jshint-preprocessor#8]
It seems that jshintrc options expects a directory, NOT a file. The file always defaults to `.jshintrc`

```
rcLoader = new RcLoader('.jshintrc', pathToJshintrc || null,
[...]
```
@https://github.com/kylewelsby/karma-jshint-preprocessor/commit/27cfcf173537f885dbec80f8210e1d0cc3625e1e#diff-168726dbe96b3ce427e7fedce31bb0bcR10

**Comment by kylewelsby** [comment]
You are right, and this contradicts the documentation.
